### ISSUE TITLE
error running jenkins build

### ISSUE THREAD

**Issue by untuned** [DaMatrix/Pork2b2tBot#15]
```
com.github.steveice10.mc.auth.exception.request.ServiceUnavailableException: Could not make request to 'https://authserver.mojang.com/authenticate'.
        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:64)
        at com.github.steveice10.mc.auth.service.AuthenticationService.loginWithPassword(AuthenticationService.java:280)
        at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:217)
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:108)
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:94)
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:90)
        at net.daporkchop.toobeetooteebot.TooBeeTooTeeBot.start(TooBeeTooTeeBot.java:188)
        at net.daporkchop.toobeetooteebot.TooBeeTooTeeBot.main(TooBeeTooTeeBot.java:95)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.Gson.assertFullConsumption(Gson.java:864)
        at com.google.gson.Gson.fromJson(Gson.java:854)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:774)
        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:62)
        ... 7 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.Gson.assertFullConsumption(Gson.java:860)
        ... 11 more
```

**Comment by DaMatrix** [comment]
that's caused either by mojang's authservers being down, or an issue with your internet connection.
