### ISSUE TITLE
instant disconnect (0.2.3)

### ISSUE THREAD

**Issue by o0ZzM4g1c** [DaMatrix/Pork2b2tBot#29]
after waiting and while I was logged in bot, I was instantly disconnected after 2b2t world loading.
bot version: 0.2.3-1.12.2

here is the log:
```
[02/12/2019 19:16:43] [Chat] [INFO] Position in queue: 4
[02/12/2019 19:16:53] [Chat] [INFO] Position in queue: 2
[02/12/2019 19:17:01] [Chat] [INFO] Connecting to the server...
[02/12/2019 19:17:02] [Chat] [INFO] <huevosrotos> > Tienda para hispanohablantes https://discord.gg/W9UP8bN
[02/12/2019 19:17:02] [Chat] [INFO] <6b9t> BLACK FRIDAY 50% OFF https://discord.gg/TtGqusM
[02/12/2019 19:17:02] [Chat] [INFO] <10Days> Ligma Balls
....
[02/12/2019 19:17:05] [Chat] [INFO] <Nollie180> >Almost every block in the game here https://discord.gg/Xn3brD2
[02/12/2019 19:17:06] [Client] [INFO] Disconnecting from server...
[02/12/2019 19:17:06] [Server] [INFO] Player disconnected: eth-west-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[02/12/2019 19:17:06] [Client] [INFO] Disconnected.
[02/12/2019 19:17:06] [Client] [INFO] Disconnected. Reason: You have lost connection to the server
[02/12/2019 19:17:06] [Client] [INFO] Reconnecting in 10
[02/12/2019 19:17:07] [Client] [INFO] Reconnecting in 9
[02/12/2019 19:17:08] [Client] [INFO] Reconnecting in 8
[02/12/2019 19:17:09] [Client] [INFO] Reconnecting in 7
[02/12/2019 19:17:10] [Client] [INFO] Reconnecting in 6
[02/12/2019 19:17:11] [Client] [INFO] Reconnecting in 5
[02/12/2019 19:17:12] [Client] [INFO] Reconnecting in 4
[02/12/2019 19:17:13] [Client] [INFO] Reconnecting in 3
[02/12/2019 19:17:14] [Server] [INFO] Player connected: null
Exception in thread "Thread-19" java.lang.NullPointerException
	at net.daporkchop.toobeetooteebot.Bot.lambda$startServer$10(Bot.java:320)
	at com.github.steveice10.mc.protocol.ServerListener$UserAuthTask.run(ServerListener.java:198)
	at java.lang.Thread.run(Thread.java:748)
[02/12/2019 19:17:14] [Client] [INFO] Reconnecting in 2
[02/12/2019 19:17:15] [Client] [INFO] Reconnecting in 1
[02/12/2019 19:17:16] [Auth] [INFO] Logging in...
[02/12/2019 19:17:16] [Auth] [SUCCESS] Logged in.
[02/12/2019 19:17:16] [Client] [INFO] Connecting to 2b2t.org:25565...
[02/12/2019 19:17:17] [Client] [SUCCESS] Connected to 2b2t.org/31.220.12.242:25565!
[02/12/2019 19:17:17] [Chat] [INFO] 2b2t is full
[02/12/2019 19:17:23] [Chat] [INFO] Position in queue: 238
[02/12/2019 19:17:33] [Chat] [INFO] Position in queue: 238
```

**Comment by DaMatrix** [comment]
investigating shortly

**Comment by DaMatrix** [comment]
i really don't see how this is possible, leaving aside the possibility of a bug in mcprotocollib itself that was previously undiscovered. are there any other exceptions or warnings earlier on in the log?

**Comment by DaMatrix** [comment]
i've tested quite a few configurations and am absolutely unable to reproduce this. would it be possible for you to send the whole log and config?

**Comment by o0ZzM4g1c** [comment]
sure. I'll test again this evening.

**Comment by o0ZzM4g1c** [comment]
I tested again just now. I connected to bot while waiting in queue, then the world loaded correctly, then I disconnected and reconnected without any problems. The bot worked well.
I don't know what happened the last time. sorry.
