### ISSUE TITLE
I tried a lots of thing but i can't fix this error

### ISSUE THREAD

**Issue by HelliosBey** [DaMatrix/Pork2b2tBot#34]
`[15/04/2020 10:07:51] [INFO] Starting Pork2b2tBot v0.0.1...
[15/04/2020 10:07:51] [Auth] [INFO] Logging in...
[15/04/2020 10:07:51] [Auth] [SUCCESS] Logged in.
[15/04/2020 10:07:51] [Client] [INFO] Connecting to 2b2t.org:25565...
[15/04/2020 10:07:53] [Client] [SUCCESS] Connected to 2b2t.org/23.145.208.9:25565!
[15/04/2020 10:07:55] [Client] [INFO] Disconnecting from server...
[15/04/2020 10:07:55] [Client] [INFO] Disconnected.
[15/04/2020 10:07:55] [Client] [ALERT] ****************************************
[15/04/2020 10:07:55] [Client] [ALERT] * 
[15/04/2020 10:07:55] [Client] [ALERT] * com.github.steveice10.mc.auth.exception.request.RequestException: Access Token can not be null or empty.
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:82)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.mc.auth.service.SessionService.joinServer(SessionService.java:104)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:48)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15/04/2020 10:07:55] [Client] [ALERT] * 	at java.lang.Thread.run(Unknown Source)
[15/04/2020 10:07:55] [Client] [ALERT] * 
[15/04/2020 10:07:55] [Client] [ALERT] ****************************************
[15/04/2020 10:07:55] [ALERT] ****************************************
[15/04/2020 10:07:55] [ALERT] * 
[15/04/2020 10:07:55] [ALERT] * java.util.concurrent.ExecutionException: com.github.steveice10.mc.auth.exception.request.RequestException: Access Token can not be null or empty.
[15/04/2020 10:07:55] [ALERT] * 	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
[15/04/2020 10:07:55] [ALERT] * 	at java.util.concurrent.CompletableFuture.get(Unknown Source)
[15/04/2020 10:07:55] [ALERT] * 	at net.daporkchop.toobeetooteebot.client.PorkClientSession.getDisconnectReason(PorkClientSession.java:49)
[15/04/2020 10:07:55] [ALERT] * 	at net.daporkchop.toobeetooteebot.Bot.start(Bot.java:221)
[15/04/2020 10:07:55] [ALERT] * 	at net.daporkchop.toobeetooteebot.Bot.main(Bot.java:123)
[15/04/2020 10:07:55] [ALERT] * Caused by: com.github.steveice10.mc.auth.exception.request.RequestException: Access Token can not be null or empty.
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:82)
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.mc.auth.service.SessionService.joinServer(SessionService.java:104)
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
[15/04/2020 10:07:55] [ALERT] * 	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:48)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15/04/2020 10:07:55] [ALERT] * 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15/04/2020 10:07:55] [ALERT] * 	at java.lang.Thread.run(Unknown Source)
[15/04/2020 10:07:55] [ALERT] * 
[15/04/2020 10:07:55] [ALERT] ****************************************
[15/04/2020 10:07:55] [INFO] Shutting down...
`

**Comment by DaMatrix** [comment]
Sounds like your authentication config is wrong somehow. Is your password correct?

**Comment by HelliosBey** [comment]
Yes it'correct.

**Comment by HelliosBey** [comment]
I'll change my password to be sure.

**Comment by HelliosBey** [comment]
It did not work.

**Comment by HelliosBey** [comment]
Will u help me?
