### ISSUE TITLE
NullPointerException whilst logging in after recovering from ratelimit

### ISSUE THREAD

**Issue by EmotionalLove** [DaMatrix/Pork2b2tBot#4]
```
[root@SashaServer ~]# java -jar 2b2tbot-0.0.1-1.12.2.jar
Attempting login with username and password...
Being rate limited, waiting...
Success!
java.lang.NullPointerException
        at net.daporkchop.toobeetooteebot.TooBeeTooTeeBot.start(TooBeeTooTeeBot.java:188)
        at net.daporkchop.toobeetooteebot.TooBeeTooTeeBot.main(TooBeeTooTeeBot.java:77)
[root@SashaServer ~]#
```
Version of java:

```
[root@SashaServer~]# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
[root@SashaServer ~]#
```

Bot starts up and runs fine using that account literally everywhere else i use it (My PC, Amazon ECS container), but not on an OVH linux machine.

If config is needed, ask me.

**Comment by DaMatrix** [comment]
Merged your PR, thanks!

I'll mess around later today and see if I can find the root cause of this.
